name: dartcheck
description: A monadic QuickCheck inspired library for Dart
version: 0.1.0
author: Oscar Ponce <wigahluk@gmail.com>
homepage: https://github.com/wigahluk/dart-check

environment:
  sdk: '2.0.0-dev.20.0'

dependencies:
  meta: ^1.1.1
  shuttlecock: ^0.4.6-dev
  tuple: ^1.0.1
  quiver_hashcode: '>=1.0.0-dev.1 <1.1.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
